feat: sección api mock en testing frontend
budacom/the-codex pull request #14
Opened 2022-12-02 18:32 UTC by rcereceda

### Contexto

Se agrega el ítem _Mocks de API calls_ en la sección Testing de la guía frontend, donde se incluye un ejemplo de uso de la librería [Mock Service Worker](https://mswjs.io/) agregada en https://github.com/budacom/buda-expo/pull/637.

### Cambios realizados

Se agrega la sección `api-mocks` dentro de `testing`, con un ejemplo de uso en los tests.

### Vistas

2022-12-06 19:48 UTC, cristiancs commented
Habría que actualizar el ejemplo por el caso borde detectado
https://github.com/budacom/buda-expo/pull/640

Y quizás sería bueno dejar como ejemplo principal el caso de 
https://github.com/budacom/buda-expo/blob/41add83938e5e4a7f1b6abcc77e737aba459aec3/src/features/news-banner/__tests__/index.spec.js#L21

Que no tiene este "hack" para esperar

2022-12-06 19:48 UTC, cristiancs requested changes
Habría que actualizar el ejemplo por el caso borde detectado
https://github.com/budacom/buda-expo/pull/640

Y quizás sería bueno dejar como ejemplo principal el caso de 
https://github.com/budacom/buda-expo/blob/41add83938e5e4a7f1b6abcc77e737aba459aec3/src/features/news-banner/__tests__/index.spec.js#L21

Que no tiene este "hack" para esperar

2022-12-16 12:41 UTC, rcereceda commented
> Habría que actualizar el ejemplo por el caso borde detectado [budacom/buda-expo#640](https://github.com/budacom/buda-expo/pull/640)
> 
> Y quizás sería bueno dejar como ejemplo principal el caso de https://github.com/budacom/buda-expo/blob/41add83938e5e4a7f1b6abcc77e737aba459aec3/src/features/news-banner/__tests__/index.spec.js#L21
> 
> Que no tiene este "hack" para esperar

@cristiancs buena! Lo [actualicé](https://github.com/budacom/the-codex/compare/21372adf7c23b2d810161638c470d06a8a921f38..52ece75590771a89e13cf4edc2fe7154b3dafe3b), dejé como ejemplo principal el caso que sólo espera el render del elemento con `waitFor`, y un ejemplo sobrescribiendo lo definido en `src/mocks/handlers.js` usando `waitForRequest`.

2022-12-16 15:41 UTC, cristiancs commented on docs/guia-frontend/testing/api-mocks.md
> +esperar la respuesta del request y así validar algún cambio en el DOM:
```suggestion
Por otra parte, si queremos sobrescribir la respuesta del request lo podemos hacer utilizando
`server.use`. Se sugiere, que vaya acompañada de la función `waitForRequest` para
esperar la respuesta del request y así validar algún cambio en el DOM:
```

2022-12-16 15:41 UTC, cristiancs approved these changes

2022-12-16 15:42 UTC, merged

2022-12-16 16:19 UTC, rcereceda commented on docs/guia-frontend/testing/api-mocks.md
> +esperar la respuesta del request y así validar algún cambio en el DOM:
No me fijé en la recomendación y le di merge, voy a actualizarlo en el PR que haga ahora 😓